[redis_nodes]
redis_ct103 ansible_host=192.168.0.231

[grafana_nodes]
grafana_ct105 ansible_host=192.168.0.226

[containers:children]
redis_nodes
grafana_nodes
brownfield_nodes

[brownfield_nodes]
pihole_ct100 ansible_host=192.168.0.202
nginxproxymanager_ct101 ansible_host=192.168.0.203
optmovementpt_ct107 ansible_host=192.168.0.210
n8n_ct109 ansible_host=192.168.0.211
gemini_bridge_ct110 ansible_host=192.168.0.212
docker_ct102 ansible_host=192.168.0.213
invoiceninja_ct112 ansible_host=192.168.0.214
prometheus_ct104 ansible_host=192.168.0.225
uptimekuma_ct106 ansible_host=192.168.0.227
ops_controller_ct900 ansible_host=192.168.0.230
prometheus_pve_exporter_ct111 ansible_host=192.168.0.232
