- name: Configure Redis
  hosts: redis_nodes
  become: yes
  tasks:
    - name: Ensure redis is installed
      apt:
        name: redis-server
        state: present
    - name: Ensure Redis is running
      systemd:
        name: redis-server
        state: started
        enabled: yes

- name: Configure Grafana (CT105)
  hosts: grafana_nodes
  become: yes
  tasks:
    - name: Ensure Grafana service is running
      systemd:
        name: grafana-server
        state: started
        enabled: yes
