- name: Configure Redis
  hosts: 192.168.0.231 # Update to your actual Redis IP
  become: yes
  tasks:
    - name: Ensure redis is installed
      apt:
        name: redis-server
        state: present
    - name: Ensure Redis is running
      systemd:
        name: redis-server
        state: started
        enabled: yes
